/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApprovalLevel = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RequestStatus = IDL.Variant({
  'submitted' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
  'draft' : IDL.Null,
  'inApproval' : IDL.Null,
});
export const Time = IDL.Int;
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ApprovalRecord = IDL.Record({
  'status' : ApprovalStatus,
  'comment' : IDL.Opt(IDL.Text),
  'approver' : IDL.Principal,
  'timestamp' : Time,
});
export const ManufacturingRequest = IDL.Record({
  'id' : IDL.Text,
  'status' : RequestStatus,
  'creator' : IDL.Principal,
  'createdAt' : Time,
  'currentApprovalLevel' : IDL.Nat,
  'updatedAt' : Time,
  'headerFields' : IDL.Text,
  'approvalRecords' : IDL.Vec(ApprovalRecord),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'assignApprover' : IDL.Func([ApprovalLevel, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllRequests' : IDL.Func([], [IDL.Vec(ManufacturingRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRequest' : IDL.Func([IDL.Text], [ManufacturingRequest], ['query']),
  'getRequestsByLevel' : IDL.Func(
      [ApprovalLevel],
      [IDL.Vec(ManufacturingRequest)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserRequests' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ManufacturingRequest)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reassignRequests' : IDL.Func(
      [ApprovalLevel, IDL.Vec(IDL.Principal)],
      [],
      [],
    ),
  'rejectRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'removeApprover' : IDL.Func([ApprovalLevel, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApprovalLevel = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RequestStatus = IDL.Variant({
    'submitted' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
    'draft' : IDL.Null,
    'inApproval' : IDL.Null,
  });
  const Time = IDL.Int;
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ApprovalRecord = IDL.Record({
    'status' : ApprovalStatus,
    'comment' : IDL.Opt(IDL.Text),
    'approver' : IDL.Principal,
    'timestamp' : Time,
  });
  const ManufacturingRequest = IDL.Record({
    'id' : IDL.Text,
    'status' : RequestStatus,
    'creator' : IDL.Principal,
    'createdAt' : Time,
    'currentApprovalLevel' : IDL.Nat,
    'updatedAt' : Time,
    'headerFields' : IDL.Text,
    'approvalRecords' : IDL.Vec(ApprovalRecord),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'assignApprover' : IDL.Func([ApprovalLevel, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllRequests' : IDL.Func([], [IDL.Vec(ManufacturingRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRequest' : IDL.Func([IDL.Text], [ManufacturingRequest], ['query']),
    'getRequestsByLevel' : IDL.Func(
        [ApprovalLevel],
        [IDL.Vec(ManufacturingRequest)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserRequests' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ManufacturingRequest)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reassignRequests' : IDL.Func(
        [ApprovalLevel, IDL.Vec(IDL.Principal)],
        [],
        [],
      ),
    'rejectRequest' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'removeApprover' : IDL.Func([ApprovalLevel, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitRequest' : IDL.Func([IDL.Text], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };