/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalLevel = bigint;
export interface ApprovalRecord {
  'status' : ApprovalStatus,
  'comment' : [] | [string],
  'approver' : Principal,
  'timestamp' : Time,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface ManufacturingRequest {
  'id' : string,
  'status' : RequestStatus,
  'creator' : Principal,
  'createdAt' : Time,
  'currentApprovalLevel' : bigint,
  'updatedAt' : Time,
  'headerFields' : string,
  'approvalRecords' : Array<ApprovalRecord>,
}
export type RequestStatus = { 'submitted' : null } |
  { 'approved' : null } |
  { 'rejected' : null } |
  { 'draft' : null } |
  { 'inApproval' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveRequest' : ActorMethod<[string, [] | [string]], undefined>,
  'assignApprover' : ActorMethod<[ApprovalLevel, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllRequests' : ActorMethod<[], Array<ManufacturingRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRequest' : ActorMethod<[string], ManufacturingRequest>,
  'getRequestsByLevel' : ActorMethod<
    [ApprovalLevel],
    Array<ManufacturingRequest>
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRequests' : ActorMethod<[Principal], Array<ManufacturingRequest>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reassignRequests' : ActorMethod<
    [ApprovalLevel, Array<Principal>],
    undefined
  >,
  'rejectRequest' : ActorMethod<[string, [] | [string]], undefined>,
  'removeApprover' : ActorMethod<[ApprovalLevel, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitRequest' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];